# Version management for MixCompare
# This file centralizes version information

# Read version from VERSION file
file(READ "${CMAKE_SOURCE_DIR}/VERSION" MIXCOMPARE_VERSION_STRING)
string(STRIP "${MIXCOMPARE_VERSION_STRING}" MIXCOMPARE_VERSION_STRING)

# Parse version components (e.g., 3.0.0-beta1)
string(REGEX MATCH "^([0-9]+)\\.([0-9]+)\\.([0-9]+)(-(.+))?$" VERSION_MATCH "${MIXCOMPARE_VERSION_STRING}")

if(VERSION_MATCH)
    set(MIXCOMPARE_VERSION_MAJOR ${CMAKE_MATCH_1})
    set(MIXCOMPARE_VERSION_MINOR ${CMAKE_MATCH_2})
    set(MIXCOMPARE_VERSION_PATCH ${CMAKE_MATCH_3})
    
    if(CMAKE_MATCH_5)
        set(MIXCOMPARE_VERSION_SUFFIX ${CMAKE_MATCH_5})
        set(MIXCOMPARE_VERSION_FULL "${MIXCOMPARE_VERSION_MAJOR}.${MIXCOMPARE_VERSION_MINOR}.${MIXCOMPARE_VERSION_PATCH}-${MIXCOMPARE_VERSION_SUFFIX}")
    else()
        set(MIXCOMPARE_VERSION_SUFFIX "")
        set(MIXCOMPARE_VERSION_FULL "${MIXCOMPARE_VERSION_MAJOR}.${MIXCOMPARE_VERSION_MINOR}.${MIXCOMPARE_VERSION_PATCH}")
    endif()
else()
    message(FATAL_ERROR "Invalid version format in VERSION file: ${MIXCOMPARE_VERSION_STRING}")
endif()

# Set project version for CMake
set(PROJECT_VERSION "${MIXCOMPARE_VERSION_MAJOR}.${MIXCOMPARE_VERSION_MINOR}.${MIXCOMPARE_VERSION_PATCH}")
set(PROJECT_VERSION_MAJOR ${MIXCOMPARE_VERSION_MAJOR})
set(PROJECT_VERSION_MINOR ${MIXCOMPARE_VERSION_MINOR})
set(PROJECT_VERSION_PATCH ${MIXCOMPARE_VERSION_PATCH})

# Export for use in build scripts (only if we have a parent scope)
if(NOT CMAKE_CURRENT_SOURCE_DIR STREQUAL CMAKE_SOURCE_DIR)
    set(MIXCOMPARE_VERSION ${MIXCOMPARE_VERSION_FULL} PARENT_SCOPE)
endif()

# Display version info
message(STATUS "MixCompare Version: ${MIXCOMPARE_VERSION_FULL}")
message(STATUS "  Major: ${MIXCOMPARE_VERSION_MAJOR}")
message(STATUS "  Minor: ${MIXCOMPARE_VERSION_MINOR}")
message(STATUS "  Patch: ${MIXCOMPARE_VERSION_PATCH}")
if(MIXCOMPARE_VERSION_SUFFIX)
    message(STATUS "  Suffix: ${MIXCOMPARE_VERSION_SUFFIX}")
endif()